GET http://localhost:5000/casa_viva/utente
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjgxOGE0YzZiNWFjYTMxYjM1YmQxNzIyIiwidXNlcl9uYW1lIjoiQWxpY2UgQ29zdGEiLCJpYXQiOjE3NDY0NjAzNDQsImV4cCI6MTc0NjUwMzU0NH0.s6r9Q5TUyODLDuc-6hSOVFE0-ZZ-9XOZFV2hfynFTpo